# Requirement: High Availability - Configures 99.9% uptime through multi-replica deployment
replicaCount: 3

# Requirement: Web Frontend Deployment - Container image configuration
image:
  repository: dollarfunding/web-frontend
  tag: latest
  pullPolicy: IfNotPresent

# Requirement: Web Frontend Deployment - Resource allocation settings
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Requirement: High Availability - Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Requirement: CDN Integration - Ingress configuration for CloudFront
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Additional CloudFront related annotations
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"

# Service configuration
service:
  type: ClusterIP
  port: 80

# Requirement: High Availability - Health check probe configuration
probes:
  liveness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 15

# Global name overrides
nameOverride: ""
fullnameOverride: ""

# NGINX specific configurations
nginx:
  workerProcesses: "auto"
  workerConnections: "1024"
  keepaliveTimeout: "65"
  clientMaxBodySize: "1m"

# Requirement: Web Frontend Deployment - Pod security context
securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

# Node selector and affinity rules for high availability
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - web-frontend
        topologyKey: kubernetes.io/hostname